services:

  catalog:
    image: "cataloge:0.0.1-SNAPSHOT"
    platform: "linux/amd64"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: catalog
      SPRING_DATASOURCE_PASSWORD: catalog
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect

  order:
    image: "order:0.0.1-SNAPSHOT"
    platform: "linux/amd64"
    ports:
      - "8081:8081"
    environment:
      CATALOG_URL: "http://catalog:8080"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: catalog
      POSTGRES_PASSWORD: catalog

  adminer:
    image: adminer
    restart: always
    ports:
      - "8085:8080"
